# Generated by Django 3.0.8 on 2021-08-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('deliverabels1', models.CharField(max_length=200, null=True)),
                ('deliverabels2', models.CharField(max_length=200, null=True)),
                ('deliverabels3', models.CharField(max_length=200, null=True)),
                ('deliverabels4', models.CharField(max_length=200, null=True)),
                ('deliverabels5', models.CharField(max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
