# Generated by Django 3.0.8 on 2021-08-17 05:41

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210817_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='moduleimage',
            field=django_resized.forms.ResizedImageField(crop=None, default='-', force_format=None, keep_meta=True, quality=100, size=[1920, 1080], upload_to=''),
        ),
    ]
