# Generated by Django 3.0.8 on 2021-08-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210817_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='moduleimage',
        ),
        migrations.AddField(
            model_name='team',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
