# Generated by Django 3.0.8 on 2021-08-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210817_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='img')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
