# Generated by Django 3.0.8 on 2020-12-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('videofile', models.FileField(null=True, upload_to='img/', verbose_name='')),
                ('price', models.IntegerField()),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
