# Generated by Django 3.0.8 on 2020-08-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='video',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='videofile',
            field=models.FileField(null=True, upload_to='img/', verbose_name=''),
        ),
    ]
