# Generated by Django 3.0.8 on 2021-08-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='price',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='videofile',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='videolink',
            field=models.URLField(null=True),
        ),
    ]
